In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

## Arrays

### 1. Basic operations

In [4]:
A = np.array([[1,1],[5,8],[4,4]])
print(A)

[[1 1]
 [5 8]
 [4 4]]


In [13]:
Z = np.ones([5,5],bool)

In [14]:
print(Z)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [20]:
E = np.arange(1,10)
print(E)

[1 2 3 4 5 6 7 8 9]


## 2. Maths operations

This is called broadcasting

In [22]:
vect_1 = np.ones(5,int)
print(vect_1)

[1 1 1 1 1]


In [23]:
print(vect_1 + 1)

[2 2 2 2 2]


In [25]:
print(vect_1 + [1,1,2,3,4])

[2 2 3 4 5]


In [26]:
print(vect_1*2)

[2 2 2 2 2]
